version: '3'
services:
    laravel_nginx:
        container_name: laravel_nginx
        image: nginx:1.15.6
        ports:
            - '3000:80'
        #生成順序の指定。完成順序までは管理できないのでコメントアウト
        #depends_on:
        #    - app
        volumes:
            - ./docker/web/nginx.conf:/etc/nginx/nginx.conf

    app:
        build: ./docker/php
        volumes:
            - .:/var/www/html/
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: sample
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
        - "3307:3307"
        volumes:
        - mysql-data:/var/lib/mysql

#コンテナ終了後もデータを保持する永続化が必要な場合は有効化
volumes:
    mysql-data: